import {
    Bookmark,
    Star,
    Heart,
    Flame,
    Crown,
    Leaf,
    Rocket,
    Sword,
    Globe,
    Trophy,
    Zap,
    Music,
    Camera,
    Coffee,
    Gem,
    Ghost,
    Smile,
    Sun,
    Moon,
    Cloud,
    Umbrella,
    Shield,
    Target,
    Flag,
    Bell,
    Lock,
    Key,
    Map,
    Compass,
    Feather,
    Brain,
    Eye,
    Swords,
    Wand,
    Skull,
    Cat,
    Dog,
    Fish,
    Dna,
    Telescope,
    Sparkles,
    Rainbow,
    Snowflake,
    Wind,
    Droplets,
    Drama,
    Scroll,
    BookOpen,
    Library,
    Pencil,
    LucideIcon,
} from "lucide-react"

export const iconMap: Record<string, LucideIcon> = {
    bookmark: Bookmark,
    star: Star,
    heart: Heart,
    flame: Flame,
    crown: Crown,
    leaf: Leaf,
    rocket: Rocket,
    sword: Sword,
    globe: Globe,
    trophy: Trophy,
    zap: Zap,
    music: Music,
    camera: Camera,
    coffee: Coffee,
    gem: Gem,
    ghost: Ghost,
    smile: Smile,
    sun: Sun,
    moon: Moon,
    cloud: Cloud,
    umbrella: Umbrella,
    shield: Shield,
    target: Target,
    flag: Flag,
    bell: Bell,
    lock: Lock,
    key: Key,
    map: Map,
    compass: Compass,
    feather: Feather,
    brain: Brain,
    eye: Eye,
    swords: Swords,
    wand: Wand,
    skull: Skull,
    cat: Cat,
    dog: Dog,
    fish: Fish,
    dna: Dna,
    telescope: Telescope,
    sparkles: Sparkles,
    rainbow: Rainbow,
    snowflake: Snowflake,
    wind: Wind,
    droplets: Droplets,
    drama: Drama,
    scroll: Scroll,
    "book-open": BookOpen,
    library: Library,
    pencil: Pencil,
}

export const CURATED_ICON_IDS = [
    "bookmark",
    "star",
    "heart",
    "flame",
    "crown",
    "leaf",
    "rocket",
    "sword",
    "globe",
] as const

export const ALL_ICON_IDS = Object.keys(iconMap)
